site_title: TonyPepe Blog
site_author: TonyPepe
git_repo_url: https://github.com/TonyPepeBear/MdNotebook

author_github_url: https://github.com/TonyPepeBear
author_facebook_url: https://github.com/TonyPepeBear
author_twitter_url: https://github.com/TonyPepeBear
